In [22]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split  #scikit-learn
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.utils import to_categorical
import pickle
from tensorflow.keras.models import load_model
from konlpy.tag import Kkma, Okt

In [23]:
pd.set_option('display.unicode.east_asian_width', True)
pd.set_option('display.max_columns', 20)
df = pd.read_csv('./output/Music_melon_All_Columns.csv')
print(df.head())
df.info()

                        title                artist genre  \
0                     VERTIGO      DRIPPIN (드리핀)  댄스   
1                       FRESH  ICHILLIN' (아이칠린)  댄스   
2                       scent                  KARL  댄스   
3          In the Violet Hour       설아 (우주소녀)  댄스   
4  월하미인 (月下美人 : LUNA)        원어스 (ONEUS)  댄스   

                                                                               lyric  \
0  달빛들이 차오를 때\n널 데려갈게 Utopia\n방안을 채우는 시들어가는 숨소리\n...        
1  You watching\n걱정은 bad 따분한 건 so bad\nWhat Huh- ...                            
2  자꾸 맴돌아 너의 향기가\n미쳐가는 걸까 드디어 내가\n언제쯤이면 널 놓을 수 있을...   
3  기억너머 잠에서 깨면\n우리의 시간들은 숨쉬고\n고요한 새벽 빛이 비추면\n별빛에 ...   
4  칠흑 같은 밤 홀로 우는 달\n그 빛 따라 네가 피고 질까\n시간을 거슬러 저 새들...      

                                                                  All_Columns  
0  VERTIGO:DRIPPIN (드리핀):달빛들이 차오를 때\n널 데려갈게 Utopi...           
1  FRESH:ICHILLIN' (아이칠린):You watching\n걱정은 bad 따...                   
2  scent:KARL:자꾸 맴돌아 너의 향기가\n미쳐가는 걸까 드디어 내가\n언제쯤이

In [27]:
X = df.All_Columns
Y = df.genre


In [28]:
with open('./output/encoder.pickle', 'rb') as f:
    encoder = pickle.load(f)
labeled_Y = encoder.transform(Y)
print(labeled_Y)
print(encoder.classes_)
print(labeled_Y[:5])
print(encoder)


[3 3 3 ... 5 5 5]
[' 록 메탈' ' 인디음악  ' 'R&B/Soul' '댄스' '랩/힙합' '발라드' '트로트  ' '포크']
[3 3 3 3 3]
LabelEncoder()


In [29]:
labeled_Y = encoder.transform(X)
print(encoder.classes_)
print(labeled_Y[:5])

ValueError: y contains previously unseen labels: "VERTIGO:DRIPPIN (드리핀):달빛들이 차오를 때\n널 데려갈게 Utopia\n방안을 채우는 시들어가는 숨소리\nNo more fear\n망설이지 마 너의 맘을 말해봐\n한 발짝 넘어가면 보여 신세계\n간절하게 원하고 갈망했던 걸\nEveryday 눈 감으면 닿을 듯해\n거침없이 부는 바람\n어서 날 Set me Free\n두려움 모두 찢어내고\nGet up Get up 깨워\n고통 속에 만들어 낼 새로운 내일\nI'm in VERTIGO 비틀거리고\n울음소리 지평선 저 끝에 닿을 때\n빛을 머금고 오직 GOTTA GO\n이 약속을 절대 잊지 마\nMake it Like I want it No doubt\n버티고 버티고 버텨낸다\n난 나를 이겨낸다\nI'm in VERTIGO GO\n상상 속에 모든 건 현실이 돼\nI'm in VERTIGO\n금빛에 물들어가\n자유를 갈망하며 RUN\nDo Walk like a king\nYes I'm 보여줄게 Reality\n상처쯤은 견뎌낼게\n내 전부를 걸었으니\nI'm in Vertigo 다시 난 돌아가\nReady set go\n날 가둬버린 상자 속을 벗어나\n정답은 멀리 있지 않아 눈을 떠\n부서질 듯 부딪혀 가슴 뛰게 둬\nNot afraid 온 세상이 널 부르게\n거침없이 부는 바람\n어서 날 Set me Free\n두려움 모두 찢어내고\nGet up Get up 깨워\n고통 속에 만들어 낼 새로운 내일\nI'm in VERTIGO 비틀거리고\n울음소리 지평선 저 끝에 닿을 때\n빛을 머금고 오직 GOTTA GO\n이 약속을 절대 잊지 마\nMake it Like I want it No doubt\n버티고 버티고 버텨낸다\n난 나를 이겨낸다\nI'm in VERTIGO GO\n상상 속에 모든 건 현실이 돼\nI'm in VERTIGO\n파도치듯 흔들거려\n위태로워 끝이 없을 듯이 표류해\n날 집어삼킬듯해\n견디고 또 싸워내\n뒤바뀐 감각이 만들어낸 환상\n걷잡을 수없이 요동치는 심장\n보름달 차오를 때\n미친 듯 울부짖어\nVERTIGO\nI'm in VERTIGO 비틀거리고\n울음소리 지평선 저 끝에 닿을 때\n빛을 머금고 오직 GOTTA GO\n이 약속을 절대 잊지 마\nMake it Like I want it No doubt\n버티고 버티고 버텨낸다\n난 나를 이겨낸다\nI'm in VERTIGO GO\n우리만의 그곳으로 데려가\n너로 물든 밤\nVERTIGO"

In [30]:
onehot_Y = to_categorical(labeled_Y)
print(onehot_Y)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]]


In [31]:
okt = Okt()
for i in range(len(X)):
    X[i] = okt.morphs(X[i], stem=True)
stopwords = pd.read_csv('./data2/stopwords.csv',index_col=0)
stopwords

for j in range(len(X)):
    words = []
    for i in range(len(X[j])):
        if len(X[j][i]) > 1:
            if X[j][i] not in list(stopwords['stopword']):
                words.append(X[j][i])
    X[j] = ' '.join(words)
print(X[1])

FRESH ICHILLIN ): You watching 걱정 bad 따분하다 so bad What Huh Ha Yeah 멋대로 step it up 시선 따라가다 Hey listening 상관없다 we don care about it Oh ei run and run run and run and move it out Huh 당당하다 ei ei 기준 따윈 바꾸다 모르다 질투 나다 괜히 심장 대고 make it over you just wanna make it over Don you just wanna make it over Let get it Feel so FRESH YES ME 오다 Go fresh 나르다 원하다 느끼다 신나다 놀다 YES ME 나다 따르다 높이 높이 올라가다 Have you ever seen anything like this Oh eh eh Feel so fresh Oh eh eh Feel so fresh 박히다 물어보다 Oh my got what that 대체 WE CHILLIN It amazing 우린 절대 재밌다 놓치다 Hey feel so fresh up feel so fresh up feel so good 차원 다르다 거야 Huh 당당하다 기준 따윈 바꾸다 모르다 질투 나다 괜히 심장 대고 make it over you just wanna make it over Don you just wanna make it over Let get it Feel so FRESH YES ME 오다 Go fresh 나르다 원하다 느끼다 신나다 놀다 YES ME 나다 따르다 높이 높이 올라가다 Have you ever seen anything like this 멋지다 보여주다 You just get out of my way 때론 과감 세상 놀래다 막다 모습 Keep it Real Feel so fresh Feel so fresh Feel so fresh ey hey Ey hey FEEL So FRESH You Just get out of my way YES 

In [32]:
with open('./output/music_melon_token (1).pickle', 'rb') as f:
    token = pickle.load(f)
tokened_X = token.texts_to_sequences(X)

In [33]:
for i in range(len(tokened_X)):
    if len(tokened_X[i]) > 1030:
        tokened_X[i] = tokened_X[i][:1030]
X_pad = pad_sequences(tokened_X, 1030)
label = encoder.classes_
model = load_model('./output/music_classfication_model_0.43542855978012085.h5')
preds = model.predict(X_pad)
predicts = []
for pred in preds:
    predicts.append(label[np.argmax(pred)])

In [34]:
df['predict'] = predicts
df['OX'] = 0
for i in range(len(df)):
    if df.loc[i, 'genre'] == df.loc[i, 'predict']:
        df.loc[i, 'OX'] = 'O'
    else:
        df.loc[i, 'OX'] = 'X'

print(df['OX'].value_counts()/len(df))
for i in range(len(df)):
    if df['genre'][i] != df['predict'][i]:
        print(df.iloc[i])

O    0.800389
X    0.199611
Name: OX, dtype: float64
title                                                      scent
artist                                                      KARL
genre                                                       댄스
lyric          자꾸 맴돌아 너의 향기가\n미쳐가는 걸까 드디어 내가\n언제쯤이면 널 놓을 수 있을...
All_Columns    scent KARL 자꾸 맴돌다 향기 걸다 드디어 이면 놓다 자꾸만 나르다 붙잡다 ...
predict                                                 R&B/Soul
OX                                                             X
Name: 2, dtype: object
title                                                        RUN
artist                                                    이준용
genre                                                       댄스
lyric          Run 내 마음보다 멀어 더\nI Can’t find way now way now\...
All_Columns    RUN 이준용 Run 마음 멀다 Can find way now way now Run...
predict                                                 R&B/Soul
OX                                                             X
Name: 9, dtype: objec

In [35]:
print(df.title[0])
print(df.iloc[0])
print(preds[0][np.argmax(preds[0])])
print(label[np.argmax(preds[0])])

VERTIGO
title                                                    VERTIGO
artist                                          DRIPPIN (드리핀)
genre                                                       댄스
lyric          달빛들이 차오를 때\n널 데려갈게 Utopia\n방안을 채우는 시들어가는 숨소리\n...
All_Columns    VERTIGO DRIPPIN 드리다 ): 달빛 차오르다 데려가다 Utopia 방안 ...
predict                                                     댄스
OX                                                             O
Name: 0, dtype: object
0.999998
댄스
